apiVersion: apps/v1
kind: Deployment
metadata:
  name: micasino-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: micasino-api
  template:
    metadata:
      labels:
        app: micasino-api
    spec:
      containers:
      - name: api
        image: us-central1-docker.pkg.dev/micasino-devops-challenge/go-challenge-repo/go-challenge-api:latest
        ports:
          - containerPort: 3000
        # Montas el .env en /app/.env
        volumeMounts:
          - name: env-file
            mountPath: /app/.env
            subPath: .env

      volumes:
        - name: env-file
          secret:
            secretName: api-env-secret  # El nombre del Secret que creaste
            items:
              - key: .env
                path: .env
