apiVersion: apps/v1
kind: Deployment
metadata:
  name: micasino-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: micasino-api
  template:
    metadata:
      labels:
        app: micasino-api
    spec:
      containers:
      - name: api
        image: us-central1-docker.pkg.dev/micasino-devops-challenge/go-challenge-repo/go-challenge-api:latest
        ports:
          - containerPort: 3000
        # Montas el .env en /app/.env
        volumeMounts:
          - name: env-file
            mountPath: /app/.env
            subPath: .env

      - name: cloud-sql-proxy
        # Usando Artifact Registry en lugar de Container Registry
        image: us-central1-docker.pkg.dev/cloud-sql-connectors/cloud-sql-proxy:2.1.0
        args:
          - "--credentials-file=/secrets/service-account.json"
          - "${{ secrets.INSTANCE_CONNECTION_NAME }}"
        volumeMounts:
          - name: service-account
            mountPath: /secrets/
            readOnly: true

      volumes:
        - name: env-file
          secret:
            secretName: api-env-secret  # El nombre del Secret que creaste
            items:
              - key: .env
                path: .env
        - name: service-account
          secret:
            secretName: cloudsql-instance-credentials
            items:
              - key: credentials.json
                path: service-account.json
