apiVersion: v1
kind: Service
metadata:
  name: micasino-api
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: micasino-api 