version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devops
    ports:
      - "5432:5432"
    networks:
      - mynet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
