version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devops
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Aquí inyectamos las variables definidas en .env
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
