version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devops
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env  # Se ha tenido que montar el archivo .env en el contenedor para que funcione
    ports:
      - "3000:3000"
    depends_on:
      - db
