apiVersion: apps/v1
kind: Deployment
metadata:
  name: micasino-api-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: micasino-api-dev
  template:
    metadata:
      labels:
        app: micasino-api-dev
    spec:
      containers:
      - name: api
        image: us-central1-docker.pkg.dev/micasino-devops-challenge/go-challenge-repo-dev/go-challenge-api:latest
        ports:
          - containerPort: 3000
        volumeMounts:
          - name: env-file
            mountPath: /app/.env
            subPath: .env
      volumes:
        - name: env-file
          secret:
            secretName: api-env-secret
            items:
              - key: .env
                path: .env 