name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        default: 'latest'

# Valores fijos para el proyecto
env:
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  GKE_CLUSTER: ${{ vars.GKE_CLUSTER }}
  GKE_ZONE: ${{ vars.GKE_ZONE }}
  IMAGE: ${{ vars.IMAGE }}
  REGION: ${{ vars.REGION }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19'
        
    - name: Test
      run: go test -v ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Autenticación con Google Cloud
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        
    # Configurar Docker para usar gcloud como credencial helper
    - name: Configure Docker
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/go-challenge-repo/${{ env.IMAGE }}:${{ github.sha }}
          ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/go-challenge-repo/${{ env.IMAGE }}:latest

  deploy-dev:
    needs: build
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@v2
    
    - uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GCP_SA_KEY }}
        
    - name: Create K8s Secrets
      run: |
        kubectl create secret generic db-credentials \
          --from-literal=host="${{ secrets.DB_HOST }}" \
          --from-literal=username="${{ secrets.DB_USERNAME }}" \
          --from-literal=password="${{ secrets.DB_PASSWORD }}" \
          --dry-run=client -o yaml | kubectl apply -f -
      
    - name: Deploy to Dev
      run: |
        kubectl apply -f .k8s/configmap.yaml
        kubectl apply -f .k8s/deployment.yaml
        kubectl apply -f .k8s/service.yaml
        kubectl set image deployment/micasino-api api=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/go-challenge-repo/${{ env.IMAGE }}:${{ github.sha }}

  deploy-prod:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    
    - uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GCP_SA_KEY }}
        
    - name: Create K8s Secrets
      run: |
        kubectl create secret generic db-credentials \
          --from-literal=host="${{ secrets.DB_HOST }}" \
          --from-literal=username="${{ secrets.DB_USERNAME }}" \
          --from-literal=password="${{ secrets.DB_PASSWORD }}" \
          --dry-run=client -o yaml | kubectl apply -f -
        
    - name: Deploy to Prod
      run: |
        kubectl apply -f .k8s/configmap.yaml
        kubectl apply -f .k8s/deployment.yaml
        kubectl apply -f .k8s/service.yaml
        kubectl set image deployment/micasino-api api=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/go-challenge-repo/${{ env.IMAGE }}:${{ github.sha }} 